=== fer2610/XML_Basico/src/cdsoferta.dtd
<!ELEMENT cd (cdoferta)*>
<!ELEMENT cdoferta (titulo|artista|pais|discografica|precio|publicacion)*>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT artista (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT discografica (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT publicacion (#PCDATA)>

=== fer2610/XML_Basico/src/cds.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE cd SYSTEM "cdsoferta.dtd">
<cd>
    <cdoferta>
        <titulo>Still got the blues</titulo>
        <artista> Gary Moore</artista>
        <pais>UK</pais>
        <discografica>Virgin Records</discografica>
        <precio>10.20</precio>
        <publicacion>1990</publicacion>
    </cdoferta>
    <cdoferta>
        <titulo>One night only</titulo>
        <artista>Bee Gees</artista>
        <pais>UK</pais>
        <discografica>Polydor</discografica>
        <precio>10.90</precio>
        <publicacion>1998</publicacion>
    </cdoferta>
    <cdoferta>
        <titulo>When a man loves a woman</titulo>
        <artista>Percy Sledge</artista>
        <pais>USA</pais>
        <discografica>Atlantic</discografica>
        <precio>8.70</precio>
        <publicacion>1987</publicacion>
    </cdoferta>
    <cdoferta>
        <titulo>Big willie style</titulo>
        <artista>Will Smith</artista>
        <pais>USA</pais>
        <discografica>Columbia</discografica>
        <precio>9.90</precio>
        <publicacion>1987</publicacion>
    </cdoferta>
    <cdoferta>
        <titulo>La cancion de Juan Perro</titulo>
        <artista>Radio Futura</artista>
        <pais>Espa√±a</pais>
        <discografica>Sony music-ariola</discografica>
        <precio>9.90</precio>
        <publicacion>1987</publicacion>
    </cdoferta>
    <cdoferta>
        <titulo>The dock of the bay</titulo>
        <artista>Otis Redding</artista>
        <pais>USA</pais>
        <discografica>Atlantic</discografica>
        <precio>7.90</precio>
        <publicacion>1987</publicacion>
    </cdoferta>
</cd>
