=== fer2610/XML_Basico/src/flora.dtd
<!ELEMENT flora (arboles)*>
<!ELEMENT arboles (nombrecientifico|nombrecomun|vegetacion|altura|formayestructura|colorenprimavera|resistenciaheladas|colorenotoño)*>
<!ELEMENT nombrecientifico (#PCDATA)>
<!ELEMENT nombrecomun (#PCDATA)>
<!ELEMENT vegetacion (#PCDATA)>
<!ELEMENT altura (#PCDATA)>
<!ELEMENT formayestructura (#PCDATA)>
<!ELEMENT colorenprimavera (#PCDATA)>
<!ELEMENT resistenciaheladas (#PCDATA)>
<!ELEMENT colorenotoño (#PCDATA)>

=== fer2610/XML_Basico/src/arboles.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE flora SYSTEM "flora.dtd">
<flora>
<arboles>
    <nombrecientifico>Acer monspessulanum</nombrecientifico>
    <nombrecomun>Arce de Montpellier, Arce menor</nombrecomun>
    <vegetacion>Caducifolio</vegetacion>
    <altura>De 6 a 10 metros</altura>
    <formayestructura>
        Copa esferica.
        Tronco principal recto con bifurcaciones.
        Ramaje colgante.
    </formayestructura>
    <colorenprimavera>Haz verde brillante, enves verde blanquecino</colorenprimavera>
    <resistenciaheladas>Heladas fuertes (Hasta -15)</resistenciaheladas>
</arboles>
<arboles>
    <nombrecientifico>Olea europea</nombrecientifico>
    <nombrecomun>Olivo</nombrecomun>
    <vegetacion>Perenne</vegetacion>
    <altura>De 8 a 15 metros</altura>
    <formayestructura>
        Copa irregular.
        Tronco principal irregular con bifurcaciones.
    </formayestructura>
</arboles>
<arboles>
    <nombrecientifico>Ramaje tortuoso</nombrecientifico>
    <colorenprimavera>Haz verde oscuro, enves verde plateado</colorenprimavera>
    <resistenciaheladas>Heladas medias (Hasta -10)</resistenciaheladas>
</arboles>
<arboles>
    <nombrecientifico>Platanus orientalis</nombrecientifico>
    <nombrecomun>Platano</nombrecomun>
    <vegetacion>Caducifolio</vegetacion>
    <altura>De 20 a 25 metros</altura>
    <formayestructura>
        Copa ovaidal.
        Tronco principal recto.
        Ramaje expandido.
    </formayestructura>
    <colorenprimavera>Haz verde medio, enves verde claro</colorenprimavera>
    <colorenotoño>Ocre</colorenotoño>
    <resistenciaheladas>Heladas fuertes (Hasta -20)</resistenciaheladas>
</arboles>
<arboles>
    <nombrecientifico>Quercus ilex</nombrecientifico>
    <nombrecomun>Encina</nombrecomun>
    <vegetacion>Perenne</vegetacion>
    <altura>en torno a 25 metros</altura>
    <formayestructura>
        Copa esferica o eleptica irregular.
        Tronco principal recto.
        Ramaje tortuoso.
    </formayestructura>
    <colorenprimavera>Plateado en hojas jovenes. En hojas antiguas, haz verde oscuro, enves plateado</colorenprimavera>
    <resistenciaheladas>Heladas fuertes (Hasta -15)</resistenciaheladas>
</arboles>
</flora>
